spring.application.name=CheckingIngredients
server.port = 8082
# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:ingredientsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (browser UI at http://localhost:8082/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console